### 텐서
- 0차원: 스칼라
- 1차원: 벡터
- 2차원: 행렬
- 3차원 이상: 텐서

### 행렬의 표현
- 행(row): 0차원 - 가로줄
  - 행의 수는 세로축의 크기
- 열(column): 1차원 - 세로줄
  - 열의 수는 가로축의 크기
- k행 n열
  - $x\in\mathbb{R}^{k\times{n}}\longrightarrow |x| = (k, n)$

### 텐서의 표현
- $k \times n \times m$ 차원의 텐서
  - $x\in\mathbb{R}^{k\times{n}\times{m}}\longrightarrow |x| = (k, n, m)$
  - k: 세로축의 크기
  - n: 가로축의 크기
  - m: 남은 축의 크기(깊이 방향)

### 데이터 사이언스: 테이블 형태(tabular)의 데이터셋
- 엑셀 데이터와 유사
  - 여러 개의 열을 가진 행들이 나열된 형태
  - 각 열은 이름을 가질 수 있음
  - 하나의 행이 데이터 단위가 됨 &rarr; 텐서
    - $|x| = (n,)$
    - 여기서 n은 열의 수 &rarr; 특징의 개수(feature)
- 이떄 하나의 데이터 즉, 행을 샘플이라 하고, N개의 샘플이 있으면 N x n 행렬이 됨
  - 여기서 하나의 샘플은 n개의 요소를 갖는 n차원의 벡터가 됨
- 딥러닝의 병렬 연산(미니 배치)은 N개의 샘플 중에서 메모리가 허락되는 만큼의 k개의 샘플 즉, k x n의 행렬을 한 번에 신경망을 통과시킴

### 자연어 처리: 문장 데이터셋
- 자연어 처리의 대상: 문장(statement)
- 단어(토큰): 의미를 가짐 &rarr; 의미를 표현하는 벡터로 표현(단어 임베딩 벡터)
- 문장: 단어(or 토큰)들이 모여 이루어진 시퀀셜(sequential) 데이터
  - 시퀀셜 데이터: 순서가 있는 데이터
- 텍스트: 단어(벡터)로 구성된 문장(행렬)의 모음 &rarr; 3차원 텐서
- N개의 문장을 갖는 텐서 x
  - $|x| = (N, l d)$
    - N: 문장의 개수
    - l: 단어의 개수 즉, 문장의 길이
    - d: 단어 특징의 개수 즉, 단어의 길이
- (의미를 나타내는 벡터인)단어의 길이는 일정 크기로 제한됨
- 자연어 문장은 길이가 정해지지 않기 때문에 문장의 길이 l은 가변적임
  - 일반적인 신경망 계층으로 표현하기 어려움
    - 순환신경망(RNN)이나 트랜스포머(transformer)를 사용함

### 컴퓨터 비전: 이미지 데이터셋
- 흑백 이미지
  - 픽셀: 0~255 사이의 값 &rarr; 스칼라
  - 한 장의 이미지: 세로축 $\times$ 가로축 크기의 픽셀로 구성 &rarr; H $\times$ W 차원의 행렬
  - 여러 장의 이미지 &rarr; 3차원의 텐서
- 컬러 이미지
  - RGB 세개의 채널로 표현되는컬러 픽셀 &rarr; 벡터
  - 한 장의 컬러 이미지: height x width x channels &rarr; 3차원 텐서
  - 여러 장의 이미지 &rarr; 4차원 텐서
- 테이블 데이터에서 열(특징)은 순서가 바뀌면 속성값이 바뀌므로 순서가 매우 중요 &rarr; 일반적
- 이미지에서 픽셀의 위치가 바뀌는 것은 이미지의 특성에 큰 영향을 미치지 않음
   - 이 특징을 반영해 선형 계층보다 합성곱신경망(CNN)을 주로 사용

### 파이토치 텐서 생성
- 값(리스트)으로 생성
- 크기로 생성

In [1]:
import torch # 파이토치 모듈 불러오기

In [2]:
# 이차원 리스트로 실수형 텐서 만들기
ft=torch.FloatTensor([[1,2],[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
lt=torch.LongTensor([[1,2],[3,4]])
lt

tensor([[1, 2],
        [3, 4]])

In [4]:
bt=torch.ByteTensor([[1,0],[0,1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [5]:
# 텐서의 크기를 주고 임의의 값으로 채움
x=torch.FloatTensor(3,2)
x

tensor([[6.5637e-27, 1.0986e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

### 넘파이 호환

In [6]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
x

array([[1, 2],
       [3, 4]])

In [8]:
# 넘파이의 ndarray를 파이토치의 텐서로 변환
x=torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [9]:
x=x.numpy()

In [10]:
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 텐서 타입 변환

In [11]:
ft

tensor([[1., 2.],
        [3., 4.]])

In [12]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [13]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

### 텐서 크기 구하기

In [14]:
# 3x2x2 텐서 x 선언
x=torch.FloatTensor([[[1,2],[3,4]],
                     [[5,6],[7,8]],
                     [[9,10],[11,12]]])
x                      

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [15]:
# 위 방식과 동일함
y=np.arange(1,13).reshape(3,2,2)
x=torch.from_numpy(y).float()
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [16]:
print(x.size()) # 크기 메소드
print(x.shape)  # 크기 속성

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [17]:
#print(y.size()) # numpy에는 size() 메소드가 없음
print(y.shape)   # numpy의 shape은 튜플 형태

(3, 2, 2)


In [18]:
print(x.size(1))
print(x.shape[1])

2
2


In [19]:
print(x.dim())
print(len(x.size()))

3
3


### 산술 연산

In [20]:
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])

In [21]:
a+b

tensor([[3., 4.],
        [6., 7.]])

In [22]:
a-b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [23]:
a**b

tensor([[ 1.,  4.],
        [27., 64.]])

In [24]:
a==b # 논리 연산

tensor([[False,  True],
        [ True, False]])

In [25]:
a>b # 비교 연산

tensor([[False, False],
        [False,  True]])

### 인플레이스 연산
- 함수명 다음에 밑줄(underscore)이 붙음
- a x b를 했을 때 나온 값을 다시 a에 저장하는 연산
- 즉, 메모리의 새로운 공간에 계산 결과가 저장되는 것이 아니라 기존 a의 공간에 계산 결과가 저장되는 것

In [26]:
a.mul(b) # a x b와 동일

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [27]:
a

tensor([[1., 2.],
        [3., 4.]])

In [28]:
a.mul_(b) # 인플레이스 연산

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [29]:
a

tensor([[ 2.,  4.],
        [ 9., 12.]])

- 연산 전후의 데이터 타입이 달라지면 오류가 발생함
- ex) a -> 실수, b -> 정수 => 오류 X<br>
$\quad$$\;$a -> 정수, b -> 실수 => 오류 O(a.mul(b)를 계산하면 a의 값이 실수가 되어야 함)
- 실수 x 정수의 연산은 결과가 실수가 되므로 원래 실수인 b의 메서드를 사용하면 문제가 발생하지 않음

In [30]:
a=torch.LongTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
#a.mul_(b)

In [31]:
b.mul(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])

### 차원 축소 연산(합, 평균)
- 벡터의 합은 스칼라 값 -> 차원이 하나 줄어듦

In [32]:
x=torch.FloatTensor([[1,2],[3,4]])

In [33]:
print(x.sum()) # 행렬 전체의 합

tensor(10.)


In [34]:
print(x.mean()) # 행렬 전체의 평균

tensor(2.5000)


In [35]:
print(x.sum(dim=0)) # 첫 번째 차원 즉, 행렬의 세로축에 대해 합 연산 수행

tensor([4., 6.])


In [36]:
print(x.sum(dim=-1)) # 뒤에서 첫 번째 차원을 의미함, 2차원까지만 존재하기에 dim=1과 동일함

tensor([3., 7.])


In [37]:
print(x.sum(dim=1))

tensor([3., 7.])


### 브로드캐스트 연산
- 크기가 다른 텐서들의 산술 연산을 가능하게 함
  - 텐서 + 스칼라
  - 텐서 + 벡터
  - 텐서 + 텐서
- numpy 브로드캐스트 규칙
  - 규칙 1: 두 배열의 차원의 수가 다르면 작은 차원을 가진 shape의 앞쪽(왼쪽)을 1로 채운다.
  - 규칙 2: 두 배열의 shape이 일치하지 않는다면, 일치하지 않는 차원에서 크기가 1인 배열이 다른 쪽 배열의 크기와 일치하도록 수정한다.
  - 규칙 3: 임의의 차원에서 크기가 일치하지 않으면서 양쪽 모두크기가 1이 아니라면 브로드캐스팅되지 않는다.

- ex 1)
  - (2,3,4) => (3,4) --> (1,3,4) --> (2,3,4)
- ex 2)
  - (2,3,4) => (3,1) --> (1,3,1) --> (2,3,4)
- ex 3)
  - (2,3,4) => (3,2) --> (1,3,2) --> (2,3,2) (X)

In [38]:
# 텐서 + 스칼라
x=torch.FloatTensor([[1,2],[3,4]])
y=1
z=x+y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [39]:
x=torch.FloatTensor([[1,2],[4,8]])
y=torch.FloatTensor([3,5])
z=x+y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


### view 함수
- 텐서의 요소 개수가 맞아야 함
- -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워짐 
- 텐서의 전체 요소(element)는 유지한 채 모양을 바꾸는 함수

In [40]:
x=torch.from_numpy(np.arange(1,13).reshape(3,2,2))
# 1~12까지의 숫자를 3x2x2의 형태로 차례대로 데이터 삽입

In [41]:
x.view(12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
x.view(3,-1)
# -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워짐

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [43]:
x.view(-1) # -1은 12와 동일

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
x.view(2,-1,2) # -1은 3과 동일

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [45]:
x.view(-1,1,3) # -1은 4와 동일 

tensor([[[ 1,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])

In [46]:
x.view(3,4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

- view() 함수의 결과는 텐서의 주소를 바꾸지 않음

In [47]:
y=x.view(3,4)

In [48]:
x.storage().data_ptr() == y.storage().data_ptr()

C:\Users\legna\AppData\Local\Temp\ipykernel_14132\3939333011.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr() == y.storage().data_ptr()


True

- 따라서 y의 값을 바꾸면 x의 값도 바뀜

In [49]:
y[0][0]=100
y

tensor([[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [50]:
x

tensor([[[100,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]],

        [[  9,  10],
         [ 11,  12]]])

- 순차적으로 선언(contiguous)된 텐서가 아닐 경우 view 함수는 오류를 발생시킴
- 오류를 방지하기 위해서는 다음과 같이 해야 함

In [51]:
x.contiguous().view(-1)

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [52]:
# reshape 함수는 contiguous 함수와 view 함수를 차례로 호출
x.reshape(-1)

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [53]:
x=torch.FloatTensor([[1,2],[3,4]])

for i in range(2):
    for j in range(2):
        print(x[i][j].data_ptr())

3367589971648
3367589971652
3367589971656
3367589971660


In [54]:
x.stride() # stride: 다음 요소로 접근하기 위해 건너뛰어야 할 요소의 수

(2, 1)

#### (2,1)이 되는 이유
##### 2: 한 행 아래로 내려가려면 메모리에서 2칸을 건너뛰어야 함
##### 1: 옆(행의 다음 인덱스)으로 가려면 1칸을 가야함

In [55]:
x.transpose_(0,1) # 전치
for i in range(2):
    for j in range(2):
        print(x[i][j].data_ptr())

3367589971648
3367589971656
3367589971652
3367589971660


In [56]:
# 전치를 하면[[1,3],[2,4]]의 형태가 되지만 메모리의 값도 같이 바뀌기 때문에 한 행 아래로 내려가려면 3을 거치지 않음
# 따라서 바로 다음 메모리인 2를 가리키므로 1칸만 움직이면 됨
x.stride()

(1, 2)

In [57]:
# x.view(-1)

### contiguous 함수
##### 텐서를 새로운 메모리 상의 인접한 주소에 인접한 값을 순서대로 할당해주는 함수
##### 메모리상에 원하는 형태로 존재한다면 새롭게 할당하지 않고 해당 텐서를 contiguous 함수의 결괏값으로 그대로 반환
##### ex) [[1,2],[3,4]] 행렬의 메모리 값 (10,20,30,40)이라 가정할 때 전치하면 [[1,3],[2,4]] 형태로 전치되고 메모리의 순서도 (10,20,30,40)임
##### -> 하지만, view 함수는 연속적인 메모리를 기준으로 읽기 때문에, 눈으로 보는 전치 순서 (10,30,20,40)와 맞지 않아 오류가 발생함
##### -> 이를 해결하기 위해 contiguous 함수를 사용하면, PyTorch가 새 메모리에 데이터를 전치 순서대로 복사하여 메모리 순서를 (10,30,20,40)으로 만들어 
##### $\quad\;$view가 올바르게 읽도록 함(메모리 순서만 재배치 된다는 의미)

In [58]:
x.contiguous().view(-1)

tensor([1., 3., 2., 4.])

### squeeze 함수
- 차원의 크기가 1인 차원을 제거함
- 원하는 차원을 지정해서 차원을 제거 할 수 있음
- 지정한 차원의 크기가 0이 아니면 원본을 그대로 돌려줌

In [59]:
x=torch.FloatTensor([[[1,2],
                      [3,4]]])

In [60]:
print(x.size())

torch.Size([1, 2, 2])


In [61]:
print(x.squeeze())

tensor([[1., 2.],
        [3., 4.]])


In [62]:
print(x.squeeze().size())

torch.Size([2, 2])


In [63]:
print(x.squeeze(0).size()) # dim = 0 -> 0번째의 크기가 1이라면 삭제 => 삭제 가능

torch.Size([2, 2])


In [64]:
print(x.squeeze(1).size()) # dim = 1 -> 1번째의 크기가 1이라면 삭제 => 삭제 불가능 및 같은 텐서 반환

torch.Size([1, 2, 2])


### unsqueeze 함수
- squeeze 함수와 반대로 크기가 1인 차원을 삽입함(삽입할 위치 지정)

In [65]:
a=torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]]])
a

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])

In [66]:
print(a.size())

torch.Size([2, 3, 1])


In [67]:
b=a.squeeze() # 차원의 크기가 1인 차원을 삭제하여 ([2,3])이 됨
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [68]:
c=b.T # 전치 행렬하여 ([3,2])가 됨
c

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [69]:
d=c.unsqueeze(0) # 0번째에 차원의 크기가 1인 차원 삽입 -> ([1,3,2]) 
d

tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]]])

In [70]:
print(a.size())
print(b.size())
print(c.size())
print(d.size())

torch.Size([2, 3, 1])
torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([1, 3, 2])


In [71]:
d=c.unsqueeze(1) # 1번째에 차원의 크기가 1인 차원 삽입 -> ([3,1,2]) 
d

tensor([[[1., 4.]],

        [[2., 5.]],

        [[3., 6.]]])

In [72]:
print(d.size())

torch.Size([3, 1, 2])


In [73]:
d=c.unsqueeze(2) # 2번째에 차원의 크기가 1인 차원 삽입 -> ([3,2,1]) 
d

tensor([[[1.],
         [4.]],

        [[2.],
         [5.]],

        [[3.],
         [6.]]])

In [74]:
print(d.size())

torch.Size([3, 2, 1])


In [75]:
d=c.unsqueeze(-1) # 뒤에서 차원의 크기가 1인 차원 삽입 -> ([3,2,1]) / 3차원이기 때문에 인덱스가 2와 -1의 사이즈가 동일함
d

tensor([[[1.],
         [4.]],

        [[2.],
         [5.]],

        [[3.],
         [6.]]])

In [76]:
print(d.size())

torch.Size([3, 2, 1])


#### 0차원 ↓, 1차원 →, 2차원 ↑ 

### 인덱싱과 슬라이싱

- numpy와 동일함

In [77]:
x=torch.FloatTensor([[[1,2],
                      [3,4]],
                     [[5,6],
                      [7,8]],
                     [[9,10],
                      [11,12]]])

In [78]:
x.size()

torch.Size([3, 2, 2])

In [79]:
print(x[0]) # 첫 번째 블록을 잘라서 반환

tensor([[1., 2.],
        [3., 4.]])


In [80]:
print(x[-1]) # 마지막 블록을 잘라서 반환

tensor([[ 9., 10.],
        [11., 12.]])


In [81]:
print(x[:,0]) # 각 블록에서 첫 번째 행을 잘라서 반환

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [82]:
print(x[:,0,:]) # 각 블록에서 첫 번째 행, 모든 열을 잘라서 반환

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [83]:
print(x[1:2,1:,:]) # 두 번째 블록에서 두 번째부터 마지막 행까지 모든 열을 잘라서 반환

tensor([[[7., 8.]]])


In [84]:
print(x[1:2, 1:, :].size())

torch.Size([1, 1, 2])


In [85]:
print(x[-1, :, 1:]) # 마지막 블록에서 모든 행, 두 번째 열부터 마지막까지를 잘라서 반환

tensor([[10.],
        [12.]])


In [86]:
print(x[:, :, 1])

tensor([[ 2.,  4.],
        [ 6.,  8.],
        [10., 12.]])


### split 함수
- 텐서를 특정 차원에 대해 원하는 크기로 잘라줌
- 원하는 크기로 나누고 마지막은 남은 것을 배분
- parameters
  - split_size: 나누는 조각의 크기
  - dim: 나누게 되는 차원

In [87]:
x=torch.FloatTensor(10,4) # 10행 4열의 텐서 생성
x

tensor([[6.6651e-27, 1.0986e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [88]:
splits = x.split(4, dim = 0) # 0번째 차원(dim=0 == 행)을 4행씩 나눔 // 4행, 4행,2행(남은 행) 즉, 3개의 텐서로 구성된 튜플

In [89]:
splits1 = x.split(2, dim = 1) # 1번째 차원(dim=1 == 열)을 2열씩 나눔 // 2열, 2열 즉, 2개의 텐서로 구성됨

In [90]:
for s in splits1:
    print(s.size())

torch.Size([10, 2])
torch.Size([10, 2])


### chunk 함수
- 크기에 상관없이 원하는 개수로 나눔
- 최대한 같은 크기로 나누고 마지막에 나머지를 배분
- parameters
  - chunk: 나누는 조각의 개수
  - dim: 나누게 되는 차원

In [91]:
x = torch.FloatTensor(8,4)

In [92]:
chunks = x.chunk(3, dim = 0)

In [93]:
chunks1 = x.chunk(2, dim = 1)

In [94]:
for c in chunks1:
    print(c.size())

torch.Size([8, 2])
torch.Size([8, 2])


### index_select 함수
- 특정 차원에서 원하는 인덱스 위치의 값만 가져옴
- parameters
  - dim: 인덱스를 지정할 차원
  - index: 정수 텐서로 저장한 인덱스 목록

In [95]:
x=torch.FloatTensor([[[1,1],
                      [2,2]],
                     [[3,3],
                      [4,4]],
                     [[5,5],
                      [6,6]]])

In [96]:
indice=torch.LongTensor([2,1]) # 어떤 블록을 먼저 가져올지 순서를 정함

In [97]:
print(x.size())

torch.Size([3, 2, 2])


In [98]:
y=x.index_select(dim=0, index=indice) # 0번째 차원(열)에서 2번째 블록을 가져오고 1번째 블록을 가져옴

- x의 내용
  - x[0] = [[1,1],[2,2]]
  - x[1] = [[3,3],[4,4]]
  - x[2] = [[5,5],[6,6]]
- 첫 번째 차원에서 인덱스 2, 1에 해당하는 요소를 뽑음
- x[2], x[1]의 순서로 요소를 가져옴 

In [99]:
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


In [100]:
print(y.size())

torch.Size([2, 2, 2])


In [101]:
indice = torch.LongTensor([1])
y = x.index_select(dim=1, index=indice)
y

tensor([[[2., 2.]],

        [[4., 4.]],

        [[6., 6.]]])

### concatenate 함수
- cat()
- 여러 텐서를 합쳐서 하나의 텐서로 만듦
- 합치는 차원을 dim으로 지정
- 합치는 차원 외 다른 차원들의 크기는 같아야 함
- parameters
  - tensors: 텐서 목록
  - dim: int, optional

In [102]:
x=torch.FloatTensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

In [103]:
y=torch.FloatTensor([[10,11,12],
                     [13,14,15],
                     [16,17,18]])

In [104]:
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [105]:
z=torch.cat([x,y], dim=0) # 첫 번째 차원(텐서의 세로축)으로 이어 붙임 
z

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [106]:
print(z.size())

torch.Size([6, 3])


In [107]:
z=torch.cat([x,y], dim=-1) # 마지막 차원(두 번째 차원 즉, 텐서의 가로축)으로 이어 붙임 
z

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

In [108]:
print(z.size())

torch.Size([3, 6])


- 만약 y 텐서가 [2, 3]이라면 dim=0으로는 cat 함수를 실행할 수 있지만 dim=-1은 차원의 크키가 맞지 않아 cat 함수를 실행할 수 없음

### stack 함수
- cat() 함수와 비슷하게 텐서를 합치는 함수
- cat() 함수와 다르게 새로운 차원을 추가하여 합치는 텐서를 쌓는 방식으로 합침
- Numpy의 stack() 메서드와 같은 방식

In [109]:
z=torch.stack([x,y]) # dim=0과 결과값 동일
z

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [110]:
print(z.size())

torch.Size([2, 3, 3])


In [111]:
z=torch.stack([x,y], dim=-1) # dim = 2와 결과값 동일
z

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])

In [112]:
print(z.size())

torch.Size([3, 3, 2])


In [113]:
z=torch.stack([x,y], dim=1)
z

tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]])

In [114]:
print(z.size())

torch.Size([3, 2, 3])


- stack() 함수는 새로운 차원을 추가(unsqueeze)해서 cat() 함수를 수행한 것과 같음

In [115]:
d=0

In [116]:
z=torch.cat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)
z

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [117]:
torch.cat([x, y], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [118]:
torch.cat([x,y], dim=-1)

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

In [119]:
torch.stack([x,y], dim=0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [120]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [121]:
torch.stack([x,y], dim=-1)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])

### Expand 함수
- 차원의 크기가 1인 차원을 원하는 크기로 늘여줌
- ex) [2, 1, 2] -> [2, 3, 2]

In [122]:
x=torch.FloatTensor([[[1,2]],[[3,4]]])
x.size()

torch.Size([2, 1, 2])

In [123]:
y=x.expand(2,3,2)
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [124]:
y.size()

torch.Size([2, 3, 2])

- cat 함수를 통해 구현할 경우 형태는 같지만 실제로는 다름

In [125]:
y=torch.cat([x] * 3, dim=1)
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

#### expand() 사용 시 주의사항
- 확장되는 차원의 데이터는 원본 데이터의 참조일 뿐, 복사가 아님
  

In [126]:
x=torch.FloatTensor([[[1,2]], [[3,4]]])
print(x.shape)
for i in range(2):
    for j in range(1):
        for k in range(2):
            print(x[i][j][k].data_ptr()) # 값이 4씩 건너 뜀

torch.Size([2, 1, 2])
3367589972608
3367589972612
3367589972616
3367589972620


In [127]:
y=x.expand(2,3,2)
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [128]:
for i in range(2):
    for j in range(3):
        for k in range(2):
            print(y[i][j][k].data_ptr()) # 4씩 건너 뛰다가 원래 값이 출력

3367589972608
3367589972612
3367589972608
3367589972612
3367589972608
3367589972612
3367589972616
3367589972620
3367589972616
3367589972620
3367589972616
3367589972620


In [129]:
x.stride()

(2, 2, 1)

In [130]:
y.stride() # 1의 메모리 값은 모두 동일 -> 같은 메모리를 가리키고 있기 때문에 다음 주소를 찾은 필요가 없음

(2, 0, 1)

In [131]:
y[0][0][0] = 100
y

tensor([[[100.,   2.],
         [100.,   2.],
         [100.,   2.]],

        [[  3.,   4.],
         [  3.,   4.],
         [  3.,   4.]]])

In [132]:
z=torch.cat([x] * 3, dim=1)
z

tensor([[[100.,   2.],
         [100.,   2.],
         [100.,   2.]],

        [[  3.,   4.],
         [  3.,   4.],
         [  3.,   4.]]])

In [133]:
z.stride()

(6, 2, 1)

In [134]:
z[1][0][0] = 20
z

tensor([[[100.,   2.],
         [100.,   2.],
         [100.,   2.]],

        [[ 20.,   4.],
         [  3.,   4.],
         [  3.,   4.]]])

In [135]:
z[0][0][0] = 50
z

tensor([[[ 50.,   2.],
         [100.,   2.],
         [100.,   2.]],

        [[ 20.,   4.],
         [  3.,   4.],
         [  3.,   4.]]])

### Random Permutation 함수
- randperm()
- 인수로 주어진 숫자로, 0부터 해당 숫자 앞까지의 정수를 임의의 순서로 텐서를 만듬
- 순서를 섞어준다는 의미에서 Numpy의 suffle()과 비슷함
- suffle()은 주어진 데이터를 섞는 것이고, randperm()은 1부터 해당 숫자까지 데이터를 생성해서 섞는 것이 다름
- 딥러닝 학습에서 데이터를 무작위 순서로 넣어주기 위해 데이터의 인덱스를 섞어주는 역할로 사용

In [136]:
x=torch.randperm(10)
x

tensor([9, 3, 8, 2, 1, 0, 5, 4, 6, 7])

### Argument Max 함수
- argmax()
- 함수의 최대값이 나오는 텐서 X의 인덱스를 반환

In [137]:
x=torch.randperm(3**3).reshape(3,3,-1)
x

tensor([[[22, 18, 12],
         [ 0,  7, 24],
         [23, 11,  2]],

        [[ 6,  3, 14],
         [ 4,  5, 20],
         [16, 21,  9]],

        [[19, 17,  1],
         [10,  8, 13],
         [25, 15, 26]]])

In [138]:
x.argmax(dim=-1) # 차원이 하나 줄어들게 됨 // x[i,j,:] 안에서 가장 큰 값의 인덱스를 출력 

tensor([[0, 2, 0],
        [2, 2, 1],
        [0, 2, 2]])

- 결과 텐서의 첫 번쨰 1은 [21, 25, 4] 중에서 제일 큰 25의 인덱스 1을 의미
- 데이터를 입력해서 연산한 결과 중에서 가장 좋은 값을 내는 데이터의 위치를 찾을 때 사용

### Top-k 함수
- topk()
- argmax() 함수는 가장 큰 값의 인덱스를 반환하는 것에 반해, topk() 함수는 가장 큰 값과 인덱스를 모두 반환
- 따라서, k=1일 때도 argmax()보다 차원이 하나 더 늘어남

In [139]:
values, indices = torch.topk(x, k=1, dim=-1)
# k = 1 => 마지막 차원에서 가장 큰 1개 값만 선택, 만약 k가 2면 2개의 값을 선택
# dim = -1 => 마지막 차원을 기준으로 선택, 값을 0,1,2로 바꿔도 shape만 달라짐

In [140]:
values # 가장 큰 값

tensor([[[22],
         [24],
         [23]],

        [[14],
         [20],
         [21]],

        [[19],
         [13],
         [26]]])

In [141]:
indices # 가장 큰 값의 인덱스

tensor([[[0],
         [2],
         [0]],

        [[2],
         [2],
         [1]],

        [[0],
         [2],
         [2]]])

In [142]:
print(values.size())

torch.Size([3, 3, 1])


### sort 함수
- 텐서를 원하는 차원 기준으로 정렬
- 결과물은 topk 함수와 동일
- true, false

In [143]:
_, indices = torch.topk(x, k=2, dim=-1)
indices.size()

torch.Size([3, 3, 2])

In [144]:
torch.sort(x, dim=-1)

torch.return_types.sort(
values=tensor([[[12, 18, 22],
         [ 0,  7, 24],
         [ 2, 11, 23]],

        [[ 3,  6, 14],
         [ 4,  5, 20],
         [ 9, 16, 21]],

        [[ 1, 17, 19],
         [ 8, 10, 13],
         [15, 25, 26]]]),
indices=tensor([[[2, 1, 0],
         [0, 1, 2],
         [2, 1, 0]],

        [[1, 0, 2],
         [0, 1, 2],
         [2, 0, 1]],

        [[2, 1, 0],
         [1, 0, 2],
         [1, 0, 2]]]))

In [145]:
target_dim=-1
values, indices = torch.topk(x,
                             k = x.size(target_dim), # 마지막 차원의 모든 값 선택
                             largest=True) # 내림차순 정렬
# 마지막 차원의 모든 값을 내림차순으로 정렬해서 가져오기
values

tensor([[[22, 18, 12],
         [24,  7,  0],
         [23, 11,  2]],

        [[14,  6,  3],
         [20,  5,  4],
         [21, 16,  9]],

        [[19, 17,  1],
         [13, 10,  8],
         [26, 25, 15]]])

### Masked Fill 함수
- masked_fill()
- 텐서 내의 원하는 부분만 특정 값으로 채움
- 원하는 위치는 마스크로 설정

In [146]:
x=torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
x

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [147]:
mask=x>4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [148]:
x.masked_fill(mask, value=100)

tensor([[  0.,   1.,   2.],
        [  3.,   4., 100.],
        [100., 100., 100.]])

### Ones, Zeros 함수
- ones(), zeros()
- ones_like(), zeros_like()
- Numpy의 함수와 같은 역할
- 차이점: Numpy 함수는 데이터의 크기를 하나의 리스트/튜플로 만들어서 넣어야 함
  <br> pytorch에서는 차원을 그대로 인수로 넣음
  - numpy -> 튜플로 줌
  - torch -> 파라미터로 줌

In [149]:
torch.ones((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [150]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [151]:
x=torch.FloatTensor([[1,2,3],
                    [4,5,6]])
x.size()

torch.Size([2, 3])

In [152]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [153]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])